FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Prisma (or similar) generation
RUN npm run db:generate

# Build only the user-app
RUN npm run build:user-app

# Start the user-app
CMD ["npm", "run", "start-user-app"]
